site_name: Red Hat Enterprise Linux Good Practices
repo_url: https://github.com/redhat-cop/rhel-good-practices/
edit_uri: blob/main/
site_author: Alessandro Rossi (alerossi@redhat.com) - Magnus Glantz (mglantz@redhat.com) - Rick Greene (rgreene@redhat.com) - Sam Wachira (swachira@redhat.com)
site_description: Web Page for the Red Hat Enterprise Linux Good Practices repository
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Red Hat Display
  features:
    - content.code.copy
    - content.tooltips
    - navigation.expand
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - assets/stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
    - Contributing to the project: contribute/contributing.md
    - Contributing guidelines: contribute/contribution-guidelines.md
    - Reviewing and testing changes: contribute/review-test-guide.md
  - System Administration:
    - Adding new persistent storage: system-administration/adding-storage.md
    - When using recursive options: system-administration/recursive-options.md
    - Creating helper scripts: system-administration/helper-scripts.md
  - Generic:
    - "Using *.d folders": generic/dotdfolders.md
  - Security:
    - Certificate management: security/certificate-management.md
    - SELinux management: security/selinux.md
  - Operational Model:
    - "What is an operational model": operational-model/intro.md
    - "Minimal Viable Product": operational-model/mvp.md
    - "2.0": operational-model/twozero.md
    - "Advanced": operational-model/advanced.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative $config_dir
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji
  - abbr
plugins:
  - macros
  - search
